version: '3'
services:
  postgresql:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: dev